### ISSUE TITLE
Explanation for removing certain message properties in the copy-headers subflow

### ISSUE THREAD

**Issue by sudarshan89** [mulesoft/anypoint-examples#1]
In the copy-headers subflow certain properties are removed, however the rationale behind removing them has not been explained, could you please explain the reason for removing each of these headers.

**Comment by pmantellini** [comment]
I assume you are referring to the Proxying a Rest API example. Given that we are copying all inbound properties (headers) from the HTTP Listener to proxy the request to the API, we need to discard the headers related to the connection itself before using the HTTP Request component to avoid connection issues, such as Content-Length or transfer-encoding. All these removed properties will be automatically generated by the HTTP Request component during the second leg of this proxy app.
You can find more information about headers for both HTTP Listener and HTTP Request components in this doc: http://www.mulesoft.org/documentation/display/current/HTTP+Connector

**Comment by sudarshan89** [comment]
Yes I was writing WRT to the proxy example and thanks for the explanation, could you please give an example of the "connection issue" that could possibly arise if the properties are not removed

**Comment by pmantellini** [comment]
Manually setting connection related headers, like Content-Length, Connection or host, is not correct and the resulting behaviour is just unpredictable. Having to remove these headers is just a consequence of copying every property from inbound to outbound to implement the proxy.
