### ISSUE TITLE
Cannot run tests of hello-world example

### ISSUE THREAD

**Issue by MarkTiedemann** [mulesoft/anypoint-examples#182]
This fails both in Anypoint Studio and when runnning `mvn test`.

<details>
<summary><code>Failed to execute goal com.mulesoft.munit.tools:munit-maven-plugin:2.1.2:test (test) on project hello-world</code> <i>(Click here to open full stacktrace)</i></summary>
<pre>
[ERROR] Failed to execute goal com.mulesoft.munit.tools:munit-maven-plugin:2.1.2:test (test) on project hello-world: Build Fail: Exception in thread "main" java.lang.RuntimeException: org.mule.maven.client.api.BundleDependenciesResolutionException: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.mulesoft.mule.distributions:mule-runtime-impl-bom:pom:4.1.1 in https://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of maven-central has elapsed or updates are forced
[ERROR] 	at org.mule.runtime.module.embedded.internal.DefaultEmbeddedContainerBuilder.build(DefaultEmbeddedContainerBuilder.java:263)
[ERROR] 	at org.mule.munit.remote.container.ContainerFactory.createContainer(ContainerFactory.java:69)
[ERROR] 	at org.mule.munit.remote.RemoteRunner.run(RemoteRunner.java:117)
[ERROR] 	at org.mule.munit.remote.RemoteRunner.main(RemoteRunner.java:92)
[ERROR] Caused by: org.mule.maven.client.api.BundleDependenciesResolutionException: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.mulesoft.mule.distributions:mule-runtime-impl-bom:pom:4.1.1 in https://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of maven-central has elapsed or updates are forced
[ERROR] 	at org.mule.maven.client.internal.AetherMavenClient.resolveBundleDescriptorDependencies(AetherMavenClient.java:221)
[ERROR] 	at org.mule.maven.client.internal.AetherMavenClient.resolveBundleDescriptorDependencies(AetherMavenClient.java:204)
[ERROR] 	at org.mule.runtime.module.embedded.internal.MavenContainerClassLoaderFactory.create(MavenContainerClassLoaderFactory.java:50)
[ERROR] 	at org.mule.runtime.module.embedded.internal.DefaultEmbeddedContainerBuilder.build(DefaultEmbeddedContainerBuilder.java:128)
[ERROR] 	... 3 more
[ERROR] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.mulesoft.mule.distributions:mule-runtime-impl-bom:pom:4.1.1 in https://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of maven-central has elapsed or updates are forced
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
[ERROR] 	at org.mule.maven.client.internal.AetherMavenClient.readArtifactDescriptor(AetherMavenClient.java:346)
[ERROR] 	at org.mule.maven.client.internal.AetherMavenClient.resolveBundleDescriptorDependencies(AetherMavenClient.java:215)
[ERROR] 	... 6 more
[ERROR] Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.mulesoft.mule.distributions:mule-runtime-impl-bom:pom:4.1.1 in https://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of maven-central has elapsed or updates are forced
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
[ERROR] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
[ERROR] 	... 11 more
</pre>
</details>

**Comment by ICfl** [comment]
Hi Mark, 
could you please share the Studio and maven version you're using?
Thank you

**Comment by MarkTiedemann** [comment]
```
$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_192, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/jre
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"
```

```
Anypoint Studio
Version: 7.3.4
Build Id: 201905081644
```

**Comment by ICfl** [comment]
Hi Mark, 
thanks for the report. It seems, you need to flavour pom.xml with repositories, which are defined in parent pom and rerun it using -U maven parameter. If you want to run it "out of the box", please import the example from Anypoint Exchange directly in the Studio.

**Comment by MarkTiedemann** [comment]
Okay, thank you, @ICfl!
