### ISSUE TITLE
Incorrect example using-transactional-scope-in-jms-to-database

### ISSUE THREAD

**Issue by sudarshan89** [mulesoft/anypoint-examples#2]
In using-transactional-scope-in-jms-to-database example the exception is thrown before the JMS outbound is involved so to that effect the JMS connector is not even involved in the transaction at run time, so we would have the same effect even if we move the JMS connector out of the transactional scope and hence I do not think this example is doing what it says ....

**Comment by pmantellini** [comment]
Thanks for the feedback, the example will be reviewed and fixed if needed.
