### ISSUE TITLE
Explanation for the defaultExpression in watermarking example

### ISSUE THREAD

**Issue by sudarshan89** [mulesoft/anypoint-examples#3]
Would like to clarify the use of the below expression in the salesforce-data-synchronization-using-watermarking-and-batch-processing example.

#[groovy: new Date(System.currentTimeMillis() - 10000).format("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", TimeZone.getTimeZone('UTC'))]

With this expression you intend to pick up the records modified in the salesforce system in the past 10 seconds only, please review my understanding ..

**Comment by pmantellini** [comment]
This is just the default expression, therefore applied only until the watermark is updated from the retrieved contacts, using the selector MAX with the expression: #[payload.LastModifiedDate]
The example provided can be replaced by any fixed date String like: "2015-05-22T22:05:05.000Z" if a cutover date is needed.

**Comment by sudarshan89** [comment]
So any date in the past wrt to the current date is valid ... am I correct. For example is current date is 2015-05-22T22:05:05.000Z then any date less than (before)  the current date is a valid.

**Comment by pmantellini** [comment]
The watermark is used in the Salesforce query:
SELECT Id,Name,LastModifiedDate FROM Contact WHERE LastModifiedDate > #[flowVars['timestamp']]
You can change the WHERE clause to use the watermark as you wish, but the typical use case is to retrieve Contacts that are newer than the timestamp saved in the previous poll. You can find more information about watermarking in this blog post:
http://blogs.mulesoft.com/data-synchronizing-made-easy-with-mule-watermarks/ 
Also, you can always check our documentation on Polling, there is a specific section for watermarking:
https://developer.mulesoft.com/docs/display/current/Poll+Reference
