### ISSUE TITLE
atomic examples/template

### ISSUE THREAD

**Issue by PaulAndersonMule** [mulesoft/anypoint-examples#41]
A feature of application-networks is that they are comprised of atomic functional units.

This example is not atomic since it couples IMAP attachment-read, transformation _and_ file-write.

Close-coupling this valuable template with DataWeave doesn’t add anything to the example - in fact it distracts. There are plenty enough DW examples out there. I recommend stripping the DataWeave from this and adding a note possibly in the flow that transformations and further processing are possible. Logging the payload is enough to demonstrate functionality

**Comment by pmantellini** [comment]
Hi Paul, the example is about getting CSV attachments from emails and converting them to XML. Our recommended way of transforming CSV format to XML is by using DataWeave transformers. Not sure why should we split this simple task into different microservices, when the example is not related to the Application Network concept and it doesn't mention API-led approach.

**Comment by PaulAndersonMule** [comment]
I'm conveying to you what customers tell me - they like to have canonical
examples  that do exactly one thing, not conflate two things (not all
emails contain CSV, and not all emails require data to be turned into CSV

On Mon, Jun 6, 2016 at 10:06 AM, Pablo Mantellini <notifications@github.com>
wrote:

> Hi Paul, the example is about getting CSV attachments from emails and
> converting them to XML. Our recommended way of transforming CSV format to
> XML is by using DataWeave transformers. Not sure why should we split this
> simple task into different microservices, when the example is not related
> to the Application Network concept and it doesn't mention API-led approach.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mulesoft/anypoint-examples/issues/41#issuecomment-223987243>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFu-1gOeFqIkvQobGSAz0wYaWx9zAbpPks5qJDdjgaJpZM4IuZH0>
> .
>



-- 
*Paul Anderson PhD*
Principal Architect
mobile: 815-451-7097
MuleSoft <http://www.mulesoft.com/>

**Comment by pmantellini** [comment]
Hi Paul, I understand the point and the feedback is always welcomed. The goal for these examples is to show some interesting use cases, and having only an email inbound with no transformations after it, does not differ much from just getting the component from the palette. In this case we are showing how to use the attachments after you got them from the email. We will take the feedback in consideration anyway and discuss with the team. Thanks!
