### ISSUE TITLE
not receiving the email

### ISSUE THREAD

**Issue by darwinganata** [mulesoft/anypoint-examples#43]
hi! please help me, I followed the instructions and ran the example, but upon checking the receiving gmail account. there is no email.

**Comment by tomas-verescak** [comment]
Hi darwinganata. I am not sure which example you are referring to but I think you are mentioning sending-a-csv-file-through-email-using-smtp. I tested the example and it works fine, so if this is the example you had trouble with, please check the SPAM folder of your e-mail account.
